"""
Alert ingestion and retrieval APIs for VulnWatch.

Phase 11:
- Accept alerts generated by the detection engine
- Prevent duplicate OPEN alerts
- Update existing OPEN alerts on repeated detections
- Protect write access with X-API-Key
- Retrieve alerts with filtering and pagination
"""

import logging
from datetime import datetime
from typing import Optional

from fastapi import APIRouter, HTTPException, Query, Security, status
from pydantic import BaseModel, Field

from database import get_connection
from security import require_api_key

logger = logging.getLogger("vulnwatch")

router = APIRouter(
    prefix="/api/v1/alerts",
    tags=["Alerts"],
)


class AlertCreate(BaseModel):
    alert_type: str = Field(min_length=1, max_length=100)
    severity: str
    status: str = "OPEN"

    source_ip: Optional[str] = None
    destination_ip: Optional[str] = None
    asset_id: Optional[int] = None

    title: str = Field(min_length=1, max_length=255)
    description: Optional[str] = None

    event_count: int = Field(default=0, ge=0)

    first_seen: datetime
    last_seen: datetime


@router.post("/import", status_code=status.HTTP_201_CREATED)
def import_alert(
    alert: AlertCreate,
    _: None = Security(require_api_key),
):
    """Create or update an alert generated by the detection engine."""

    allowed_alert_types = {
        "SSH_BRUTE_FORCE",
        "PORT_SCAN",
    }

    allowed_severities = {
        "CRITICAL",
        "HIGH",
        "MEDIUM",
        "LOW",
        "INFO",
        "UNKNOWN",
    }

    allowed_statuses = {
        "OPEN",
        "IN_PROGRESS",
        "RESOLVED",
    }

    alert_type = alert.alert_type.upper()
    severity = alert.severity.upper()
    alert_status = alert.status.upper()

    if alert_type not in allowed_alert_types:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "Invalid alert_type. Use one of: "
                "SSH_BRUTE_FORCE, PORT_SCAN"
            ),
        )

    if severity not in allowed_severities:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "Invalid severity. Use one of: "
                "CRITICAL, HIGH, MEDIUM, LOW, INFO, UNKNOWN"
            ),
        )

    if alert_status not in allowed_statuses:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(
                "Invalid status. Use one of: "
                "OPEN, IN_PROGRESS, RESOLVED"
            ),
        )

    with get_connection() as conn:
        with conn.cursor() as cur:

            # ---------------------------------------------------------
            # 1. Resolve asset automatically from destination IP
            # ---------------------------------------------------------

            asset_id = alert.asset_id

            if asset_id is None and alert.destination_ip:
                cur.execute(
                    """
                    SELECT id
                    FROM assets
                    WHERE ip_address = %(destination_ip)s::inet
                    LIMIT 1;
                    """,
                    {
                        "destination_ip": alert.destination_ip,
                    },
                )

                asset_row = cur.fetchone()

                if asset_row:
                    asset_id = asset_row[0]

            # ---------------------------------------------------------
            # 2. Check for an existing OPEN alert
            # ---------------------------------------------------------

            if alert_status == "OPEN":
                cur.execute(
                    """
                    SELECT
                        id,
                        severity,
                        status,
                        event_count,
                        first_seen,
                        last_seen,
                        created_at
                    FROM alerts
                    WHERE alert_type = %(alert_type)s
                      AND source_ip = %(source_ip)s::inet
                      AND destination_ip = %(destination_ip)s::inet
                      AND status = 'OPEN'
                    LIMIT 1;
                    """,
                    {
                        "alert_type": alert_type,
                        "source_ip": alert.source_ip,
                        "destination_ip": alert.destination_ip,
                    },
                )

                existing_row = cur.fetchone()

                # -----------------------------------------------------
                # 3. Existing OPEN alert -> update instead of duplicate
                # -----------------------------------------------------

                if existing_row:
                    cur.execute(
                        """
                        UPDATE alerts
                        SET
                            severity = %(severity)s,
                            asset_id = %(asset_id)s,
                            title = %(title)s,
                            description = %(description)s,
                            event_count = %(event_count)s,
                            first_seen = LEAST(
                                first_seen,
                                %(first_seen)s
                            ),
                            last_seen = GREATEST(
                                last_seen,
                                %(last_seen)s
                            )
                        WHERE id = %(id)s
                        RETURNING
                            id,
                            alert_type,
                            severity,
                            status,
                            source_ip::text,
                            destination_ip::text,
                            asset_id,
                            title,
                            description,
                            event_count,
                            first_seen,
                            last_seen,
                            created_at;
                        """,
                        {
                            "severity": severity,
                            "asset_id": asset_id,
                            "title": alert.title,
                            "description": alert.description,
                            "event_count": alert.event_count,
                            "first_seen": alert.first_seen,
                            "last_seen": alert.last_seen,
                            "id": existing_row[0],
                        },
                    )

                    row = cur.fetchone()

                    logger.info(
                        "Existing OPEN alert updated: id=%s type=%s",
                        row[0],
                        alert_type,
                    )

                    return {
                        "message": "Existing alert updated",
                        "alert": {
                            "id": row[0],
                            "alert_type": row[1],
                            "severity": row[2],
                            "status": row[3],
                            "source_ip": row[4],
                            "destination_ip": row[5],
                            "asset_id": row[6],
                            "title": row[7],
                            "description": row[8],
                            "event_count": row[9],
                            "first_seen": row[10],
                            "last_seen": row[11],
                            "created_at": row[12],
                        },
                    }

            # ---------------------------------------------------------
            # 4. Insert new alert
            # ---------------------------------------------------------

            cur.execute(
                """
                INSERT INTO alerts (
                    alert_type,
                    severity,
                    status,
                    source_ip,
                    destination_ip,
                    asset_id,
                    title,
                    description,
                    event_count,
                    first_seen,
                    last_seen
                )
                VALUES (
                    %(alert_type)s,
                    %(severity)s,
                    %(status)s,
                    %(source_ip)s,
                    %(destination_ip)s,
                    %(asset_id)s,
                    %(title)s,
                    %(description)s,
                    %(event_count)s,
                    %(first_seen)s,
                    %(last_seen)s
                )
                RETURNING
                    id,
                    alert_type,
                    severity,
                    status,
                    source_ip::text,
                    destination_ip::text,
                    asset_id,
                    title,
                    description,
                    event_count,
                    first_seen,
                    last_seen,
                    created_at;
                """,
                {
                    "alert_type": alert_type,
                    "severity": severity,
                    "status": alert_status,
                    "source_ip": alert.source_ip,
                    "destination_ip": alert.destination_ip,
                    "asset_id": asset_id,
                    "title": alert.title,
                    "description": alert.description,
                    "event_count": alert.event_count,
                    "first_seen": alert.first_seen,
                    "last_seen": alert.last_seen,
                },
            )

            row = cur.fetchone()

    logger.info(
        "Alert created: id=%s type=%s severity=%s asset_id=%s",
        row[0],
        alert_type,
        severity,
        asset_id,
    )

    return {
        "message": "Alert imported successfully",
        "alert": {
            "id": row[0],
            "alert_type": row[1],
            "severity": row[2],
            "status": row[3],
            "source_ip": row[4],
            "destination_ip": row[5],
            "asset_id": row[6],
            "title": row[7],
            "description": row[8],
            "event_count": row[9],
            "first_seen": row[10],
            "last_seen": row[11],
            "created_at": row[12],
        },
    }


@router.get("")
def list_alerts(
    alert_type: Optional[str] = Query(default=None),
    source_ip: Optional[str] = Query(default=None),
    destination_ip: Optional[str] = Query(default=None),
    severity: Optional[str] = Query(default=None),
    status: Optional[str] = Query(default=None),
    limit: int = Query(default=100, ge=1, le=500),
    offset: int = Query(default=0, ge=0),
):
    """
    Retrieve alerts with optional filtering and pagination.

    Results are ordered newest first.
    """

    filters = []
    params = {}

    if alert_type:
        normalized_alert_type = alert_type.upper()

        if normalized_alert_type not in {
            "SSH_BRUTE_FORCE",
            "PORT_SCAN",
        }:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=(
                    "Invalid alert_type. Use one of: "
                    "SSH_BRUTE_FORCE, PORT_SCAN"
                ),
            )

        filters.append("alert_type = %(alert_type)s")
        params["alert_type"] = normalized_alert_type

    if source_ip:
        filters.append("source_ip = %(source_ip)s::inet")
        params["source_ip"] = source_ip

    if destination_ip:
        filters.append("destination_ip = %(destination_ip)s::inet")
        params["destination_ip"] = destination_ip

    if severity:
        normalized_severity = severity.upper()

        if normalized_severity not in {
            "CRITICAL",
            "HIGH",
            "MEDIUM",
            "LOW",
            "INFO",
            "UNKNOWN",
        }:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=(
                    "Invalid severity. Use one of: "
                    "CRITICAL, HIGH, MEDIUM, LOW, INFO, UNKNOWN"
                ),
            )

        filters.append("severity = %(severity)s")
        params["severity"] = normalized_severity

    if status:
        normalized_status = status.upper()

        if normalized_status not in {
            "OPEN",
            "IN_PROGRESS",
            "RESOLVED",
        }:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=(
                    "Invalid status. Use one of: "
                    "OPEN, IN_PROGRESS, RESOLVED"
                ),
            )

        filters.append("status = %(status)s")
        params["status"] = normalized_status

    where_clause = ""

    if filters:
        where_clause = "WHERE " + " AND ".join(filters)

    params["limit"] = limit
    params["offset"] = offset

    with get_connection() as conn:
        with conn.cursor() as cur:
            cur.execute(
                f"""
                SELECT
                    id,
                    alert_type,
                    severity,
                    status,
                    source_ip::text,
                    destination_ip::text,
                    asset_id,
                    title,
                    description,
                    event_count,
                    first_seen,
                    last_seen,
                    created_at
                FROM alerts
                {where_clause}
                ORDER BY last_seen DESC, id DESC
                LIMIT %(limit)s
                OFFSET %(offset)s;
                """,
                params,
            )

            rows = cur.fetchall()

    alerts = []

    for row in rows:
        alerts.append(
            {
                "id": row[0],
                "alert_type": row[1],
                "severity": row[2],
                "status": row[3],
                "source_ip": row[4],
                "destination_ip": row[5],
                "asset_id": row[6],
                "title": row[7],
                "description": row[8],
                "event_count": row[9],
                "first_seen": row[10],
                "last_seen": row[11],
                "created_at": row[12],
            }
        )

    return {
        "count": len(alerts),
        "limit": limit,
        "offset": offset,
        "alerts": alerts,
    }