-- ==========================================
-- VulnWatch Database Schema
-- VAPT + SOC Security Monitoring
-- ==========================================

-- ==========================================
-- NMAP SCANS
-- ==========================================

-- Stores each Nmap scan
CREATE TABLE scans (
    id BIGSERIAL PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    target INET NOT NULL,
    nmap_command TEXT NOT NULL,
    scanner_ip INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- ASSETS
-- ==========================================

-- Stores discovered hosts/assets
CREATE TABLE assets (
    id BIGSERIAL PRIMARY KEY,
    ip_address INET NOT NULL UNIQUE,
    mac_address MACADDR,
    hostname TEXT,
    os TEXT,
    os_accuracy SMALLINT CHECK (os_accuracy BETWEEN 0 AND 100),
    first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- SERVICES
-- ==========================================

-- Stores ports/services discovered on each asset
CREATE TABLE services (
    id BIGSERIAL PRIMARY KEY,

    asset_id BIGINT NOT NULL
        REFERENCES assets(id)
        ON DELETE CASCADE,

    port INTEGER NOT NULL
        CHECK (port BETWEEN 1 AND 65535),

    protocol TEXT NOT NULL
        CHECK (protocol IN ('tcp', 'udp')),

    service_name TEXT,
    product TEXT,
    version TEXT,
    cpe TEXT,

    state TEXT NOT NULL DEFAULT 'open'
        CHECK (state IN ('open', 'closed', 'filtered', 'unknown')),

    first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    last_scan_id BIGINT
        REFERENCES scans(id)
        ON DELETE SET NULL,

    CONSTRAINT unique_asset_service
        UNIQUE (asset_id, port, protocol)
);

-- ==========================================
-- VULNERABILITY MANAGEMENT
-- ==========================================

-- Stores each CVE only once
CREATE TABLE vulnerabilities (
    id BIGSERIAL PRIMARY KEY,

    cve_id TEXT NOT NULL UNIQUE,

    description TEXT,

    cvss_version TEXT
        CHECK (cvss_version IN ('2.0', '3.0', '3.1')),

    cvss_score NUMERIC(3,1)
        CHECK (cvss_score BETWEEN 0.0 AND 10.0),

    cvss_vector TEXT,

    severity TEXT NOT NULL
        CHECK (
            severity IN (
                'CRITICAL',
                'HIGH',
                'MEDIUM',
                'LOW',
                'NONE',
                'UNKNOWN'
            )
        ),

    cwe TEXT,

    published TIMESTAMPTZ,

    last_modified TIMESTAMPTZ,

    nvd_synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Maps vulnerabilities to discovered services
CREATE TABLE service_vulnerabilities (
    id BIGSERIAL PRIMARY KEY,

    service_id BIGINT NOT NULL
        REFERENCES services(id)
        ON DELETE CASCADE,

    vulnerability_id BIGINT NOT NULL
        REFERENCES vulnerabilities(id)
        ON DELETE CASCADE,

    matched_cpe TEXT,

    match_source TEXT NOT NULL DEFAULT 'nvd-cpe',

    first_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    last_seen TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT unique_service_vulnerability
        UNIQUE (service_id, vulnerability_id)
);

-- ==========================================
-- SECURITY EVENTS / SOC
-- ==========================================

-- Stores normalized security events collected
-- from authorized lab security logs.
CREATE TABLE security_events (
    id BIGSERIAL PRIMARY KEY,

    asset_id BIGINT
        REFERENCES assets(id)
        ON DELETE SET NULL,

    event_type TEXT NOT NULL,

    event_time TIMESTAMPTZ NOT NULL,

    source_ip INET,

    destination_ip INET,

    protocol TEXT,

    source_port INTEGER
        CHECK (
            source_port IS NULL
            OR source_port BETWEEN 1 AND 65535
        ),

    destination_port INTEGER
        CHECK (
            destination_port IS NULL
            OR destination_port BETWEEN 1 AND 65535
        ),

    username TEXT,

    severity TEXT NOT NULL DEFAULT 'LOW'
        CHECK (
            severity IN (
                'CRITICAL',
                'HIGH',
                'MEDIUM',
                'LOW',
                'INFO',
                'UNKNOWN'
            )
        ),

    raw_log TEXT,

    source TEXT NOT NULL DEFAULT 'lab-log',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- ALERTS / DETECTION
-- ==========================================

-- Stores alerts generated by the SOC detection engine.
CREATE TABLE alerts (
    id BIGSERIAL PRIMARY KEY,

    alert_type TEXT NOT NULL
        CHECK (
            alert_type IN (
                'SSH_BRUTE_FORCE',
                'PORT_SCAN'
            )
        ),

    severity TEXT NOT NULL
        CHECK (
            severity IN (
                'CRITICAL',
                'HIGH',
                'MEDIUM',
                'LOW',
                'INFO',
                'UNKNOWN'
            )
        ),

    status TEXT NOT NULL DEFAULT 'OPEN'
        CHECK (
            status IN (
                'OPEN',
                'IN_PROGRESS',
                'RESOLVED'
            )
        ),

    source_ip INET,

    destination_ip INET,

    asset_id BIGINT
        REFERENCES assets(id)
        ON DELETE SET NULL,

    title TEXT NOT NULL,

    description TEXT,

    event_count INTEGER NOT NULL DEFAULT 0
        CHECK (event_count >= 0),

    first_seen TIMESTAMPTZ NOT NULL,

    last_seen TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- INDEXES
-- ==========================================

CREATE INDEX idx_services_asset_id
    ON services(asset_id);

CREATE INDEX idx_services_last_scan_id
    ON services(last_scan_id);

CREATE INDEX idx_services_cpe
    ON services(cpe);

CREATE INDEX idx_scans_started_at
    ON scans(started_at);

CREATE INDEX idx_vulnerabilities_severity
    ON vulnerabilities(severity);

CREATE INDEX idx_vulnerabilities_cve_id
    ON vulnerabilities(cve_id);

CREATE INDEX idx_service_vulnerabilities_service_id
    ON service_vulnerabilities(service_id);

CREATE INDEX idx_service_vulnerabilities_vulnerability_id
    ON service_vulnerabilities(vulnerability_id);

CREATE INDEX idx_security_events_asset_id
    ON security_events(asset_id);

CREATE INDEX idx_security_events_event_time
    ON security_events(event_time);

CREATE INDEX idx_security_events_event_type
    ON security_events(event_type);

CREATE INDEX idx_security_events_source_ip
    ON security_events(source_ip);

CREATE INDEX idx_security_events_destination_ip
    ON security_events(destination_ip);

CREATE INDEX idx_alerts_alert_type
    ON alerts(alert_type);

CREATE INDEX idx_alerts_status
    ON alerts(status);

CREATE INDEX idx_alerts_severity
    ON alerts(severity);

CREATE INDEX idx_alerts_source_ip
    ON alerts(source_ip);

CREATE INDEX idx_alerts_destination_ip
    ON alerts(destination_ip);

CREATE INDEX idx_alerts_asset_id
    ON alerts(asset_id);

CREATE INDEX idx_alerts_last_seen
    ON alerts(last_seen);

-- Prevent duplicate OPEN alerts for the same
-- detection type and source/destination pair.
CREATE UNIQUE INDEX uq_open_alert_source_destination
    ON alerts (
        alert_type,
        source_ip,
        destination_ip
    )
    WHERE status = 'OPEN';


-- ==========================================
-- PHASE 12: CORRELATION ENGINE
-- ==========================================

-- Links an existing SOC alert with an existing
-- vulnerability/service vulnerability on the same asset.
CREATE TABLE IF NOT EXISTS correlations (
    id BIGSERIAL PRIMARY KEY,

    asset_id BIGINT NOT NULL
        REFERENCES assets(id)
        ON DELETE CASCADE,

    alert_id BIGINT NOT NULL
        REFERENCES alerts(id)
        ON DELETE CASCADE,

    service_vulnerability_id BIGINT
        REFERENCES service_vulnerabilities(id)
        ON DELETE SET NULL,

    finding_id BIGINT,

    correlation_type TEXT NOT NULL
        CHECK (
            correlation_type IN (
                'ASSET_VULNERABILITY_ALERT'
            )
        ),

    priority TEXT NOT NULL
        CHECK (
            priority IN (
                'CRITICAL',
                'HIGH',
                'MEDIUM',
                'LOW',
                'INFO'
            )
        ),

    title TEXT NOT NULL,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ==========================================
-- CORRELATION INDEXES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_correlations_asset_id
    ON correlations(asset_id);

CREATE INDEX IF NOT EXISTS idx_correlations_alert_id
    ON correlations(alert_id);

CREATE INDEX IF NOT EXISTS idx_correlations_service_vulnerability_id
    ON correlations(service_vulnerability_id);

CREATE INDEX IF NOT EXISTS idx_correlations_finding_id
    ON correlations(finding_id);

CREATE INDEX IF NOT EXISTS idx_correlations_priority
    ON correlations(priority);

CREATE INDEX IF NOT EXISTS idx_correlations_created_at
    ON correlations(created_at);

-- Prevent the same alert and service vulnerability
-- from producing duplicate correlation records.
CREATE UNIQUE INDEX IF NOT EXISTS uq_correlations_alert_vulnerability
    ON correlations(
        alert_id,
        service_vulnerability_id
    );